/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/current-projects': RouteRecordInfo<'/posts/current-projects', '/posts/current-projects', Record<never, never>, Record<never, never>>,
    '/posts/tamu-grades-writeup': RouteRecordInfo<'/posts/tamu-grades-writeup', '/posts/tamu-grades-writeup', Record<never, never>, Record<never, never>>,
    '/posts/tamugd-writeup': RouteRecordInfo<'/posts/tamugd-writeup', '/posts/tamugd-writeup', Record<never, never>, Record<never, never>>,
    '/posts/using-cloudflare': RouteRecordInfo<'/posts/using-cloudflare', '/posts/using-cloudflare', Record<never, never>, Record<never, never>>,
    '/posts/web-optimization': RouteRecordInfo<'/posts/web-optimization', '/posts/web-optimization', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
    '/resume': RouteRecordInfo<'/resume', '/resume', Record<never, never>, Record<never, never>>,
  }
}
